# Generated by Django 3.2.6 on 2021-09-30 15:24

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[accounts.validators.validate_CNPJ, accounts.validators.valida_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[accounts.validators.validate_CPF], verbose_name='CPF'),
        ),
    ]
