# Generated by Django 3.2.6 on 2021-10-21 14:26

import company.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, validators=[company.validators.validate_CNPJ, company.validators.valida_cnpj], verbose_name='CNPJ')),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=90, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('clients', models.ManyToManyField(to='accounts.Client')),
            ],
        ),
    ]
